name: Fetch PR Changes
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.md"

jobs:
  fetch-pr-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Fetch PR Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.number }}

          # Fetch PR details focusing on MD files
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files")

          # Extract and process only MD files
          echo "$RESPONSE" | jq -r '.[] | select(.filename | endswith(".md")) | {filename: .filename, patch: .patch} | @base64' | while read -r file; do
            decoded=$(echo "$file" | base64 --decode)
            filename=$(echo "$decoded" | jq -r '.filename')
            patch=$(echo "$decoded" | jq -r '.patch')
            
            # Create a comment with the changes
            comment="### Changes in \`$filename\`\n\n\`\`\`diff\n$patch\n\`\`\`"
            
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
              -d "{\"body\": $(echo "$comment" | jq -R -s '.')}"
          done
