name: Test PullProof
on: pull_request

jobs:
  test-pullproof:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run PullProof Action
        uses: SyedSibtainRazvi/PullProof@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
