name: Fetch PR Changes
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  fetch-pr-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Fetch PR Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.number }}

          # Fetch PR details
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")

          # Extract Diff URL
          DIFF_URL=$(echo "$RESPONSE" | jq -r '.diff_url')

          # Fetch Diff Content
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3.diff" \
            "$DIFF_URL" > full_pr_diff.diff

          # Extract only added/modified lines (skip lines starting with '-')
          grep -E '^\+' full_pr_diff.diff | sed 's/^+//' > pr_changes.txt

      - name: Upload PR Changes
        uses: actions/upload-artifact@v3
        with:
          name: pr-changes
          path: pr_changes.txt
